sonar.projectKey=zowe_zlux-editor
sonar.organization=zowe
sonar.projectName=ZLUX Editor Application
sonar.links.scm=https://github.com/zowe/zlux-editor
sonar.sources=webClient,webClient/src/app
sonar.tests=webClient/src/app
sonar.test.inclusions=**/*.spec.ts
sonar.coverage.exclusions=**/*.js
sonar.javascript.lcov.reportPaths=webClient/coverage/lcov.info
