sonar.projectKey=zlux:zlux-editor
sonar.projectName=ZLUX Editor Application
sonar.projectVersion=1.0.0
sonar.sources=webClient
sonar.links.scm=https://github.com/zowe/zlux-editor
sonar.sources=webClient/src/app
sonar.tests=webClient/src/app
sonar.test.inclusions=**/*.spec.ts
sonar.coverage.exclusions=**/*.js
