sonar.projectKey=zowe-zlux-editor
sonar.organization=zowe
sonar.projectName=ZLUX Editor Application
sonar.links.scm=https://github.com/zowe/zlux-editor
sonar.sources=webClient/
sonar.tests=webClient/src/app
sonar.test.inclusions=**/*.spec.ts
sonar.coverage.exclusions=**/*.js
sonar.javascript.lcov.reportPaths=webClient/coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.projectVersion=1.0.0
sonar.host.url=https://sonarcloud.io
