name: OSSF Scorecard Using Actions
on:
  schedule:
    - cron: '0 6 1 * *'  # Runs at 06:00 UTC on the 1st day of every month
  pull_request:
    branches: [ v3.x/staging ]               
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write
  issues: write
jobs:
  scorecard:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zowe/zlux-build/.github/actions/ossf-scorecard-sarif-action@ScoreCardFC
        with:
          enabled_checks: TokenPermissionsID,PinnedDependenciesID,BranchProtectionID,ContributorsID,DangerousWorkflowID
          results_file: results.sarif
          filtered_results_file: filteredResults.sarif
 
      - name: Create GitHub Issue for Scorecard Findings
        if: github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GHA_CREATE_ISSUE }}
          repository: zowe/zlux
          title: "OSSF Scorecard Results - ${{ github.run_id }}"
          content-filepath: scorecard-summary.md
