name: OSSF Scorecard Using Actions
on:
  push:
    branches:
      - 'v*.x/staging'
  pull_request:
    branches: 
      - 'v*.x/staging'
      - 'v*.x/rc'
      - 'v*.x/master'
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  schedule:
    - cron:  '30 1 * * 6'

permissions:
  contents: read
  security-events: write
  issues: write
jobs:
  scorecard:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zowe/zlux-build/.github/actions/ossf-scorecard-sarif-action@ScoreCardFC
        with:
          enabled_checks: TokenPermissionsID,PinnedDependenciesID,BranchProtectionID,ContributorsID,DangerousWorkflowID
          results_file: results.sarif
          filtered_results_file: filteredResults.sarif
          
      - name: Comment on Pull Request with Scorecard summary
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: scorecard-summary.md

      - name: Create GitHub Issue for Scorecard Findings
        if: github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "OSSF Scorecard Results - ${{ github.run_id }}"
          content-filepath: scorecard-summary.md
